# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

version: "3.8"
x-aws-vpc: "${AWS_VPC_ID}"
x-aws-loadbalancer: "${AWS_LB_NAME}"
networks:
  default:
    external: true
    name: "${AWS_SG_ID}"
volumes:
  adminapp-bulk-hashcache:
services:
  api:
    image: "${ODSAPI_IMAGE}"
    deploy:
      replicas: 3
      resources:
            limits:
              cpus: '1'
              memory: '2Gb'
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_PORT: "${PGPORT}"
      ODS_POSTGRES_HOST: "${PGHOST}"
      ADMIN_POSTGRES_HOST: "${PGHOST}"
      API_MODE: "SharedInstance"
      ApiSettings__PathBase: "api"
      TPDM_ENABLED: "true"
      API_HEALTHCHECK_TEST: "wget --no-verbose --tries=1 --spider http://localhost || exit 1"
    ports:
    - target: 80
      x-aws-protocol: http
    container_name: ed-fi-ods-api
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost || exit 1"
      start_period: "60s"
      retries: 3

  swagger:
    image: "${SWAGGER_IMAGE}"
    environment:
      POPULATED_KEY: "${POPULATED_KEY}"
      POPULATED_SECRET: "${POPULATED_SECRET}"
      WebApiVersionUrl: "${API_URL}"
      PathBase: "docs"
      ASPNETCORE_URLS: "http://+:8081"
      Urls: "http://+:8081"
      SWAGGER_HEALTHCHECK_TEST: "wget --no-verbose --tries=1 --spider http://localhost:8081 || exit 1"
    ports:
    - target: 8081
      x-aws-protocol: http
    depends_on:
      - api
    container_name: ed-fi-swagger
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8081 || exit 1"
      start_period: "60s"
      retries: 3
  adminapp:
    image: "${ADMINAPP_IMAGE}"
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_PORT: "5432"
      ODS_POSTGRES_HOST: "${PGHOST}"
      ADMIN_POSTGRES_HOST: "${PGHOST}"
      API_MODE: "SharedInstance"
      API_EXTERNAL_URL: "${API_URL}"
      ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
      ADMINAPP_VIRTUAL_NAME: "adminapp"
      API_INTERNAL_URL: ${API_URL}
      ADMINAPP_HEALTHCHECK_TEST: "wget --no-verbose --tries=1 --spider http://localhost:8082 || exit 1"
      ASPNETCORE_URLS: "http://+:8082"
      ADMIN_USER: "${ADMIN_USER}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
    ports:
    - target: 8082
      x-aws-protocol: http
    depends_on:
      - api
    container_name: ed-fi-ods-adminapp
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8082 || exit 1"
      start_period: "120s"
      retries: 3
    volumes:
      - adminapp-bulk-hashcache:/app/BulkUploadHashCache
